#!/usr/bin/with-contenv sh

echo
echo '             NNNNNNNNNNNN                      NNNNNNNNNNNN'
echo '             NNNNNNNNNNNNNNNNN             NNNNNNNNNNNNNNNN'
echo '              NNNNNNNNNNNNNNNNNNNN   NNNNNNNNNNNNNNNNNNNNN'
echo '                NNNNNNNNNNNNNNNNNNN NNNNNNNNNNNNNNNNNNNN'
echo '                  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN'
echo '                      NNNNNNNNNNNNNNNNNNNNNNNNNNNN'
echo '                           NNNNNNNNNNNNNNNNNN'
echo '                              NNNNNNNNNNNN'
echo '                               NNNNNNNNNN'
echo '                                NNNNNNNN'
echo '                                NNNNNNN'
echo '                                NNNNNNN'
echo '                                 NNNNNN'
echo ' hsssssm    dsssssh     ssssss     N      ssssss     hsssssd    Nsssssh'
echo ' hsssssd    Nsssssy     ysssssd          dsssssy     ysssssm    msssssh'
echo ' dsssssh     ssssssm    msssssshm      Nhssssssm    Nssssss     hsssssd'
echo ' Nssssss     dsssssy     mssssssssyhhyssssssssm     ysssssh    NssssssN'
echo '  hsssssh     ysssssyN    NhsssssssssssssssshN     hsssssy     dsssssy'
echo '  Nssssssm    Nysssssym     NdhssssssssssydN     mysssssyN    mssssssN'
echo '   dssssssN    NysssssshN       NmmmmmmN       NhssssssyN    Nssssssd'
echo '    hssssssm     dsssssssydN                Ndysssssssd     mssssssh'
echo '     hssssssd     NhssssssssyhdmN      NmdhysssssssshN     dssssssh'
echo '      dssssssym     NdsssssssssssssssssssssssssssydN     Nyssssssd'
echo '       mssssssshN      mdyssssssssssssssssssssydN      Nhssssssym'
echo '         dsssssssym        NmdhyyssssssyyhdmN        mysssssssh'
echo '          Nhsssssssshm                            mhsssssssshN'
echo '            NhsssssssssydmN                  NmdyssssssssshN'
echo '               mhsssssssssssyhhddmmmmmmddhhyssssssssssshm'
echo '                  mhyssssssssssssssssssssssssssssssyhm'
echo '                     NmdyyssssssssssssssssssssyhdmN'
echo '                           NmmddhhhhhhhhhdmmN'
echo

cd /app/api
exec s6-setuidgid funkwhale daphne config.asgi:application >> /var/log/funkwhale/funkwhale.log 2>&1
