#!/usr/bin/with-contenv sh

echo
echo '............NNNNNNNNNN............................NNNNNNNNN.............'
echo '............NmmmmmmmmmmmmNN..................NNmmmmmmmmmmmmN............'
echo '............NmmmmmmmmmmmmmmmmmNN.......NNNmmmmmmmmmmmmmmmmm.............'
echo '.............NmmmmmmmmmmmmmmmmmmmmN.NmmmmmmmmmmmmmmmmmmmmmN.............'
echo '..............NmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmN...............'
echo '................NNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmN.................'
echo '...................NNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNN...................'
echo '........................NNNmmmmmmmmmmmmmmmmmmNNN........................'
echo '............................NmmmmmmmmmmmmmNN............................'
echo '..............................NmmmmmmmmmmN..............................'
echo '...............................Nmmmmmmmm................................'
echo '................................mmmmmmmm................................'
echo '................................mmmmmmmN................................'
echo '................................NmmmmmmN................................'
echo '.hsssssm....dsssssh.....ssssss...NNmmN....ssssss.....hsssssd....Nsssssh.'
echo '.hsssssd....Nsssssy.....ysssssd..........dssssss.....ysssssm....msssssh.'
echo '.dsssssh.....ssssssm....msssssshm......Nhssssssm....Nssssss.....hsssssd.'
echo '.Nssssss.....dsssssy.....mssssssssyhhyssssssssm.....ysssssh....NssssssN.'
echo '..hsssssh.....ysssssyN....NhsssssssssssssssshN.....ysssssy.....hsssssy..'
echo '..Nssssssm....Nsssssssm.....NdhssssssssssydN.....myssssssN....mssssssN..'
echo '...dssssssN....NysssssshN.......NmmddmmN.......NhssssssyN....Nssssssd...'
echo '....hssssssm.....dsssssssydN................Ndysssssssd.....mssssssh....'
echo '.....hssssssd.....NhssssssssshdmN......NmdhssssssssshN.....dssssssh.....'
echo '......dssssssym.....NdssssssssssssssssssssssssssssdN.....Nyssssssd......'
echo '.......mssssssshN......mdyssssssssssssssssssssydN......Nhsssssssm.......'
echo '.........dsssssssym........mmdyyyssssssyyhdmN........mysssssssh.........'
echo '..........Nhsssssssshm............................mhsssssssshN..........'
echo '............NhsssssssssydmN..................NmdyssssssssshN............'
echo '...............mhsssssssssssyyhddmmmmmmddhyyssssssssssshm...............'
echo '..................mhyssssssssssssssssssssssssssssssyhm..................'
echo '.....................NmdyssssssssssssssssssssssydmN.....................'
echo '...........................NmmddhhhyyhhhhdmmN...........................'
echo

cd /app/api
exec s6-setuidgid funkwhale daphne config.asgi:application --access-log /var/log/funkwhale/daphne.log
