#!/usr/bin/with-contenv sh

# helper functions
run_user() { su - postgres -c "$1"; }
run_psql() { run_user "psql -c \"$1\""; }

# does db already exist? start server
if [[ -f "$DATABASE_PATH/PG_VERSION" ]]; then
	run_user "pg_ctl -D $DATABASE_PATH start"
else
	# initialize db
	run_user "initdb $DATABASE_PATH && touch /tmp/db-created"

	# start server
	run_user "pg_ctl -D $DATABASE_PATH start"

	# setup
	run_psql "CREATE DATABASE funkwhale WITH ENCODING 'UTF-8';"
	run_psql 'CREATE USER funkwhale;'
	run_psql 'GRANT ALL PRIVILEGES ON DATABASE funkwhale TO funkwhale;'
	run_psql 'ALTER USER funkwhale WITH SUPERUSER;'
	run_psql 'CREATE EXTENSION unaccent;'
fi

