#!/usr/bin/with-contenv sh

# Helper function.
run() { s6-setuidgid funkwhale $@; }

# Database already exists.
if [[ -f '/data/data/PG_VERSION' ]]; then
	chmod -R 0700 /data/data  # set permissions
	run pg_ctl -D /data/data start  # start server

# Database needs to be created.
else
	run initdb /data/data  # initialize db
	chmod -R 0700 /data/data  # set permissions
	run pg_ctl -D /data/data start  # start server

	run createdb -E 'UTF-8'
	run psql -c 'GRANT ALL PRIVILEGES ON DATABASE funkwhale TO funkwhale;'
	run psql -c 'ALTER USER funkwhale WITH SUPERUSER;'
	run psql -c 'CREATE EXTENSION unaccent;'
fi
